### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by fukai007** [xuanjinliang/fis3-postpackager-simplify#1]
fis3 release debug -cw

 [ERROR] Load /Users/fukai/testH5/test-two-html/fis-conf.js error: /Users/fukai/testH5/test-two-html/fis-conf.js:97
         fis.plugin('simplify',{
            ^
Unexpected token . 
 /Users/fukai/testH5/test-two-html/fis-conf.js:97
         fis.plugin('simplify',{
            ^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.cli.run (/usr/local/lib/node_modules/fis3/lib/cli.js:199:7)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/fis3/bin/fis.js:36:11)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/fis3/node_modules/liftoff/index.js:197:12)

 Check this out: https://github.com/fex-team/fis3-errors/issues/2

npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "debug"
npm ERR! node v0.12.7
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! cpd@1.0.0 debug: `fis3 release debug -cw`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cpd@1.0.0 debug script 'fis3 release debug -cw'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cpd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     fis3 release debug -cw
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cpd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cpd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fukai/testH5/test-two-html/npm-debug.log

**Comment by xuanjinliang** [comment]
感觉不是插件问题，而是fis-conf.js有错
